// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PedidosGarcomMvc.Data;

namespace PedidosGarcomMvc.Migrations
{
    [DbContext(typeof(PedidosGarcomMvcContext))]
    [Migration("20210116135258_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PedidosGarcomMvc.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bebida");

                    b.Property<int>("Mesa");

                    b.Property<string>("Prato");

                    b.Property<int>("Quantidade_Bebida");

                    b.Property<int>("Quantidade_Prato");

                    b.Property<string>("Solicitante");

                    b.HasKey("Id");

                    b.ToTable("Pedido");
                });
#pragma warning restore 612, 618
        }
    }
}
