// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PedidosGarcomMvc.Data;

namespace PedidosGarcomMvc.Migrations
{
    [DbContext(typeof(PedidosGarcomMvcContext))]
    partial class PedidosGarcomMvcContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PedidosGarcomMvc.Models.Copa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bebida");

                    b.Property<int>("Mesa");

                    b.Property<int>("Quantidade");

                    b.HasKey("Id");

                    b.ToTable("Copa");
                });

            modelBuilder.Entity("PedidosGarcomMvc.Models.Cozinha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Mesa");

                    b.Property<string>("Prato");

                    b.Property<int>("Quantidade");

                    b.HasKey("Id");

                    b.ToTable("Cozinha");
                });

            modelBuilder.Entity("PedidosGarcomMvc.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bebida");

                    b.Property<int>("CopaId");

                    b.Property<int>("CozinhaId");

                    b.Property<int>("Mesa");

                    b.Property<string>("Prato");

                    b.Property<int>("Quantidade_Bebida");

                    b.Property<int>("Quantidade_Prato");

                    b.Property<string>("Solicitante");

                    b.HasKey("Id");

                    b.HasIndex("CopaId");

                    b.HasIndex("CozinhaId");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("PedidosGarcomMvc.Models.Pedido", b =>
                {
                    b.HasOne("PedidosGarcomMvc.Models.Copa", "Copa")
                        .WithMany("Pedidos")
                        .HasForeignKey("CopaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PedidosGarcomMvc.Models.Cozinha", "Cozinha")
                        .WithMany("Pedidos")
                        .HasForeignKey("CozinhaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
